language: node_js
node_js:
- node
before_script:
  - npm install
cache: npm
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    repo: ktalebian/travis-play