language: node_js
node_js:
- node
before_script:
  - npm install
cache: npm
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "npm run publish:public"
  skip_cleanup: true
  on:
    tags: true
    branch: main
    repo: ktalebian/travis-play
branches:
  - main