#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BIN_DIR="$CWD/node_modules/.bin"
LERNA="$BIN_DIR/lerna"

# Runs script but quits if script exists with non-zero exit code
function run_script() {
  eval "$@"
  if [ $? -eq 1 ] ; then
    echo "Script '$@' failed - exiting"
    exit $?
  fi
}

echo "//registry.npmjs.org/:email=\${NPM_EMAIL}" >> $HOME/.npmrc 2> /dev/null
echo "//registry.npmjs.org/:username=\${NPM_USERNAME}" >> $HOME/.npmrc 2> /dev/null
echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
echo "printing home"
echo $HOME
echo "lsing home"
ls -al $HOME
echo "printing whoami"
npm whoami
echo $PWD
echo "printing ls"
ls -al .
run_script $LERNA run clean
run_script npm install --no-package-lock
run_script npm run build
run_script $LERNA publish from-git --yes --no-verify-access