#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BIN_DIR="$CWD/node_modules/.bin"
LERNA="$BIN_DIR/lerna"

# Runs script but quits if script exists with non-zero exit code
function run_script() {
  eval "$@"
  if [ $? -eq 1 ] ; then
    echo "Script '$@' failed - exiting"
    exit $?
  fi
}


npm config set registry https://registry.npmjs.org
npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"

run_script $LERNA run clean
run_script npm install --no-package-lock
run_script npm run build
run_script $LERNA publish from-git --yes