#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BIN_DIR="$CWD/node_modules/.bin"
LERNA="$BIN_DIR/lerna"
RELEASE_IT="$BIN_DIR/relase-it"

LERNA version minor --yes
RELEASE_IT -c releaseit.json --ci minor