name: Feature Reqyest
description: Request a new Feature
title: "[Feature Request]: "
labels: [bug, triage]
assignees:
- ktalebian
body:
- type: input
  id: summary
  attributes:
    label: Summary
    description: A clear and concise description of what the feature you are requesting is.
    placeholder: It would be amazing to add a way to do ...
  validations:
    required: true
